addons:
  apt:
    packages:
      - google-chrome-stable
    sources:
      - google-chrome
after_success:
- codecov --file ./karma_coverage_reports/coverage-final.json
before_install:
- pip install codecov
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
branches:
  only:
  - master
cache:
  directories:
    - ./node_modules/
    - ./third_party/
    - ./tools/
dist: trusty
install: true
script:
- bash scripts/run_karma_tests.sh --single-run
- bash scripts/run_linter.sh
- bash scripts/run_e2e_tests.sh
sudo: required
